In [2]:
!pip install pandas

import pandas as pd

df=pd.read_csv('C:\\Users\\hp\\Downloads\\archive\\sales_data.csv')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   str
 2   Sales_Rep             1000 non-null   str
 3   Region                1000 non-null   str
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   str
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   str
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   str
 12  Sales_Channel         1000 non-null   str
 13  Region_and_Sales_Rep  1000 non-null   str
dtypes: float64(4), int64(2), str(8)
memory usage: 109.5 KB

In [5]:
df.describe(include='all')

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
count,1000.000000,1000,1000,1000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000,1000.00000,1000,1000,1000
unique,NaN,340,5,4,NaN,NaN,4,NaN,NaN,2,NaN,3,2,20
top,NaN,2023-11-14,David,North,NaN,NaN,Clothing,NaN,NaN,New,NaN,Credit Card,Retail,North-Eve
freq,NaN,8,222,267,NaN,NaN,268,NaN,NaN,504,NaN,345,512,64
mean,1050.128000,NaN,NaN,NaN,5019.265230,25.355000,NaN,2475.304550,2728.440120,NaN,0.15239,NaN,NaN,NaN
std,29.573505,NaN,NaN,NaN,2846.790126,14.159006,NaN,1417.872546,1419.399839,NaN,0.08720,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,100.120000,1.000000,NaN,60.280000,167.120000,NaN,0.00000,NaN,NaN,NaN
25%,1024.000000,NaN,NaN,NaN,2550.297500,13.000000,NaN,1238.380000,1509.085000,NaN,0.08000,NaN,NaN,NaN
50%,1051.000000,NaN,NaN,NaN,5019.300000,25.000000,NaN,2467.235000,2696.400000,NaN,0.15000,NaN,NaN,NaN
75%,1075.000000,NaN,NaN,NaN,7507.445000,38.000000,NaN,3702.865000,3957.970000,NaN,0.23000,NaN,NaN,NaN
max,1100.000000,NaN,NaN,NaN,9989.040000,49.000000,NaN,4995.300000,5442.150000,NaN,0.30000,NaN,NaN,NaN

In [6]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [7]:
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(' ','_')

In [8]:
df.columns

Index(['product_id', 'sale_date', 'sales_rep', 'region', 'sales_amount',
       'quantity_sold', 'product_category', 'unit_cost', 'unit_price',
       'customer_type', 'discount', 'payment_method', 'sales_channel',
       'region_and_sales_rep'],
      dtype='str')

In [9]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in .\AppData\Roaming\Python\Python313\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python313\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\Downloads\archive\sales_data.csv")

username = "postgres"
password = quote_plus("anshi@2004")
host = "localhost"
port = "5432"
database = "sales_data"  # <-- Change this back to your proper database name!

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}",
    isolation_level="AUTOCOMMIT"
)
table_name = "sales"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into the proper '{database}' database!")

Data successfully loaded into the proper 'sales_data' database!